<p>When a constructor/destructor has a function-try-block, the code inside of the catch clause will be executed after the object has been destroyed
(if the object was partially constructed when the exception was thrown, this part will be destroyed before going in the catch block). Therefore, the
members of the object are not available, and it is undefined behavior to access them.</p>
<p>Since the lifetime of a static member is greater than that of the object itself, so a static member can be accessed from the catch code.</p>
<h2>Noncompliant Code Example</h2>
<pre>
class A {
public:
  int i;
  A ( ) try {
    // Action that might raise an exception
  } catch ( ... ) {
    if ( i == 0 ) { // Noncompliant, i has been destroyed
      // ...
    }
  }
  ~A ( ) try {
    // Action that might raise an exception
  } catch ( ... ) {
    if ( i == 0 ) { // Noncompliant
      // ...
    }
  }
};
</pre>
<h2>See</h2>
<ul>
  <li> MISRA C++:2008, 15-3-3 </li>
  <li> <a href="https://wiki.sei.cmu.edu/confluence/x/_3s-BQ">CERT, ERR53-CPP.</a> - Do not reference base classes or class data members in a
  constructor or destructor function-try-block handler </li>
</ul>